# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/satori/go.uuid",
  "github.com/ipfs/go-verifcid",
  #"github.com/ipfs/go-log",
  "github.com/gxed/pubsub",
  #"github.com/ipfs/go-ipfs-delay",
  "github.com/ipfs/go-ipfs-exchange-interface",
  "github.com/ipfs/go-ipfs-flags",
  "github.com/ipfs/go-ipfs-pq",
  "github.com/ipfs/go-ipfs-routing/mock",
  #"github.com/libp2p/go-libp2p-netutil",
  #"github.com/libp2p/go-testutil",
  #"github.com/ipfs/go-datastore",
  #"github.com/libp2p/go-libp2p"
]

# To keep us on latest since maintainer stopped releasing versions
[[constraint]]
  name = "github.com/hashicorp/memberlist"
  branch = "master"

# To avoid pulling old gorp version, we use master of our fork
[[constraint]]
  name = "github.com/mattermost/gorp"
  branch = "master"

# Fork for adding our own method to viper EnvSettings
[[constraint]]
  name = "github.com/mattermost/viper"
  source = "https://github.com/mattermost/viper"
  branch = "mattermost"

# Keep back because of breaking API changes
[[constraint]]
  name = "github.com/segmentio/analytics-go"
  version = "2.1.1"

# Lock to control when plugins use new versions
[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "e45cbeb79f0411b1cfedd3f226ff69d5d433c762"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a4620f9913d19f03a6bf19b2f304daaaf83ea130"

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.0"

#[[constraint]]
  #name = "github.com/c3systems/c3-sdk-go"
  #version = "0.0.6"

[[constraint]]
  name = "github.com/c3systems/c3-go"
  branch = "develop"

[[constraint]]
  name = "github.com/ipfs/go-verifcid"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[prune]
  go-tests = true
  unused-packages = true
